FROM python:3.12-slim

WORKDIR /usr/src/core

COPY requirements.txt .

RUN pip install --no-cache-dir -r requirements.txt

COPY ./core .
COPY entrypoint.sh .

RUN chmod +x entrypoint.sh

ENTRYPOINT ["./entrypoint.sh"]

CMD [ "fastapi", "run", "--host", "0.0.0.0", "--port", "8000" ]